Andrew
SevanBadal/box pull request #4
Opened 2023-02-09 02:26 UTC by AndrewSepic

box sevo "Here you go. Remove multiple ids and edits to help screen & readme"

2023-02-09 16:00 UTC, SevanBadal requested changes
Let's resolve the batch delete before merging.

2023-02-09 16:00 UTC, SevanBadal commented on index.js
> +    for(const id of listOfIds) {
Let's refactor this to use batch delete with `in()`
```
const { data, error } = await supabase
  .from('some_table')
  .delete()
  .in('id', ['1', '2']) // any number of ids
```

2023-02-10 20:26 UTC, AndrewSepic commented on index.js
> +    for(const id of listOfIds) {
Done!

2023-02-10 21:14 UTC, SevanBadal approved these changes

2023-02-10 21:14 UTC, merged